# Generated by Django 5.2.6 on 2025-09-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_task_name_task_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Untitled Task', max_length=200),
        ),
    ]
